[PDND-38] Repository review for DAF Kafka Consumer
italia/daf-kafka-consumer pull request #15
Opened 2019-07-03 14:09 UTC by CrisTofani

Added:

- New Readme file
- Authors file
- issue_template
- License

2019-07-03 18:18 UTC, giux78 approved these changes

2019-07-09 14:54 UTC, altroisi requested changes
fix some typos in README.md

2019-07-09 14:54 UTC, altroisi commented on README.md
> +<!--> Insert here a brief description of what your repository contains. Insert also links to the last release, the official page, the extended documentation, and other useful external resources.-->
```suggestion
```

2019-07-09 14:54 UTC, altroisi commented on README.md
> +<!--> Insert here an extended description of the project with informations about context, goals, stakeholders, use cases, and finally the role of the project within the PDND with links to other repos
```suggestion
```

2019-07-09 14:54 UTC, altroisi commented on README.md
> +<!--> Insert here informations about files and folders structure, branch model adopted and release policy.-->
```suggestion
```

2019-07-09 14:54 UTC, altroisi commented on README.md
> +master.
and _dev_ branch?

2019-07-09 14:54 UTC, altroisi commented on README.md
> +> Insert here a brief documentation to use this project as an end-user (not a developer) if applicable, including pre-requisites and internal and external dependencies. Insert a link to an extended d
```suggestion
```

2019-07-09 14:54 UTC, altroisi commented on README.md
> +<!--> Insert here a brief documentation for the developer to build, test and contribute. Insert a link to an extended documentation (developer manual) if present.-->
```suggestion
```

2019-07-09 14:54 UTC, altroisi commented on README.md
> +Contributions are welcome. Feel free to [open issues](./issues) and submit a [pull request](./pulls) at any time, but please read [our handbook](https://github.com/teamdigitale/daf-handbook) first.
```suggestion
Contributions are welcome. Feel free to [open issues](../../issues) and submit a [pull request](../../pulls) at any time, but please read [our handbook](https://github.com/teamdigitale/daf-handbook) first.
```

2019-07-10 09:32 UTC, CrisTofani commented on README.md
> +master.
Added the reference to _dev_ branch

2019-07-10 09:32 UTC, merged